
CREATE TABLE CONTRACT_EMP(
	EMP_ID NUMBER(9) NOT NULL,
	SC_ID VARCHAR2(20) NOT NULL,
	ANNUAL_SALARY NUMBER(38) NOT NULL,
	PRIMARY KEY(EMP_ID, SC_ID),
	FOREIGN KEY (EMP_ID, SC_ID) REFERENCES EMPLOYEE(EMP_ID, SC_ID)
);
CREATE TABLE CUSTOMER(
    C_ID NUMBER(38) NOT NULL, 
    C__STATUS NUMBER(38)
    C_NAME VARCHAR2(20), 
    SC_ID VARCHAR2(20) NOT NULL, 
    ADDRESS VARCHAR2(30),
    EMAIL_ADDRESS VARCHAR2(30),
    PHONE_NUMBER NUMBER,
    USERNAME VARCHAR2(20),
    PASSWORD VARCHAR2(20)
    PRIMARY KEY(C_ID, SC_ID), 
    FOREIGN KEY (SC_ID) REFERENCES SERVICE_CENTER(SC_ID) ON DELETE CASCADE
);
CREATE TABLE ELECTRICAL_SERVICES (
  S_NO NUMBER(38) NOT NULL,
  PRIMARY KEY(S_NO),
  FOREIGN KEY (S_NO) REFERENCES SERVICES(S_NO) ON DELETE CASCADE
);
CREATE TABLE EMPLOYEE(
    EMP_ID NUMBER(9) NOT NULL,
    SC_ID VARCHAR2(20) NOT NULL,
    EMP_NAME VARCHAR2(50) NOT NULL,
    EMP_EMAIL VARCHAR2(50),
    EMP_ADDRESS VARCHAR2(100),
    EMP_CONTACT VARCHAR2(10),
    EMP_ROLE VARCHAR2(20) CONSTRAINT role_type CHECK (emp_role in('MANAGER','RECEPTIONIST','MECHANIC')),
    EMP_STARTDATE DATE,
    EMP_COMPENSATION NUMBER,
    PRIMARY KEY(EMP_ID, SC_ID),
    FOREIGN KEY (SC_ID) REFERENCES SERVICE_CENTER(SC_ID) ON DELETE CASCADE
);
CREATE TABLE EMPLOYEE_AUTH (
    EMP_ID NUMBER(15) NOT NULL,
    SC_ID VARCHAR2(20) NOT NULL,
    EMP_ROLE VARCHAR2(20) CONSTRAINT role CHECK (emp_role in('MANAGER','RECEPTIONIST','MECHANIC')),
    USERNAME VARCHAR2(20) NOT NULL,
    PASSWORD VARCHAR2(20),
    PRIMARY KEY(USERNAME),
    FOREIGN KEY (EMP_ID, SC_ID) REFERENCES EMPLOYEE(emp_id,sc_id) ON DELETE CASCADE
 );
CREATE TABLE ENGINE_SERVICES (
  S_NO NUMBER(38) NOT NULL,
  PRIMARY KEY(S_NO),
  FOREIGN KEY (S_NO) REFERENCES SERVICES(S_NO) ON DELETE CASCADE
);
CREATE TABLE EXHAUST_SERVICES (
  S_NO NUMBER(38) NOT NULL,
  PRIMARY KEY(S_NO),
  FOREIGN KEY (S_NO) REFERENCES SERVICES(S_NO) ON DELETE CASCADE
);
CREATE TABLE HOURLY_EMP(
	EMP_ID NUMBER(9) NOT NULL,
	SC_ID VARCHAR2(20) NOT NULL,
	HOURLY_RATE NUMBER(38) NOT NULL,
	PRIMARY KEY(EMP_ID, SC_ID),
	FOREIGN KEY (EMP_ID, SC_ID) REFERENCES EMPLOYEE(EMP_ID, SC_ID)
);
CREATE TABLE H_AND_AC_SERVICES(
  S_NO NUMBER(38) NOT NULL,
  PRIMARY KEY(S_NO),
  FOREIGN KEY (S_NO) REFERENCES SERVICES(S_NO) ON DELETE CASCADE
);
CREATE TABLE MAINTENANCE (
 SCHEDULE_NAME CHAR(1) NOT NULL,
 S_NO NUMBER(38) NOT NULL,
 SERVICE_NAME VARCHAR2(50),
 SERVICE_TYPE VARCHAR2(5),
 PRIMARY KEY(S_NO, SCHEDULE_NAME),
 FOREIGN KEY (S_NO) REFERENCES SERVICES(S_NO) ON DELETE CASCADE
);
CREATE TABLE MAINTENANCE_DURATION (
 SCHEDULE_NAME CHAR(1) NOT NULL,
 DURATION NUMBER,
 S_NO NUMBER(38) NOT NULL,
 PRIMARY KEY(SCHEDULE_NAME),
 FOREIGN KEY (S_NO) REFERENCES SERVICES(S_NO) ON DELETE CASCADE
);
CREATE TABLE MANAGER(
    MANAGER_ID NUMBER NOT NULL, 
    SC_ID VARCHAR2(20) NOT NULL,
    M_NAME VARCHAR2(20), 
    SALARY NUMBER,
    USERNAME VARCHAR2(20),
    PASSWORD VARCHAR2(20)
    ADDRESS VARCHAR2(50),
    EMAIL_ADDRESS VARCHAR2(20),
    PHONE_NUMBER NUMBER,
    PRIMARY KEY(MANAGER_ID, SC_ID), 
    FOREIGN KEY (MANAGER_ID, SC_ID) REFERENCES EMPLOYEE(EMP_ID, SC_ID) ON DELETE CASCADE
);
CREATE TABLE MODEL(
  MODEL_NAME VARCHAR2(20),
);
CREATE TABLE PRICE_CHECK(
    SC_ID VARCHAR2(20) NOT NULL,
    MANUFACTURER VARCHAR2(20),
    PRICE NUMBER,
    S_NO NUMBER(38) NOT NULL,
    PRIMARY KEY(SC_ID,MANUFACTURER, PRICE, S_NO), 
    FOREIGN KEY (SC_ID) REFERENCES EMPLOYEE(SC_ID) ON DELETE CASCADE,
    FOREIGN KEY (S_NO) REFERENCES SERVICES(S_NO) ON DELETE CASCADE
);
CREATE TABLE REPAIR (
  SERVICE_NAME VARCHAR2(20),
  S_NO NUMBER(38) NOT NULL,
  DURATION NUMBER,
  PRIMARY KEY(S_NO),
  FOREIGN KEY (S_NO) REFERENCES SERVICES(S_NO) ON DELETE CASCADE
);
CREATE TABLE SCHEDULED_SERVICES(
    C_ID NUMBER(38), 
    FULL_NAME VARCHAR2(20),
    SC_ID VARCHAR2(20), 
    VIN VARCHAR(8),
    MANUFACTURER VARCHAR2(20),
    MILEAGE NUMBER(38),
    SCHEDULE_SERVICE VARCHAR2(20),
    WEEK VARCHAR2(20),
    DAY VARCHAR2(20),
    START_TIME_SLOT VARCHAR2(20),
    END_TIME_SLOT VARCHAR2(20),
    MECHANIC_ID NUMBER,
    INVOICE_STATUS VARCHAR2(20),
    INVOICE_ID VARCHAR(10),
    AMOUNT_PAID VARCHAR(10),
    AMOUNT_REMAINED VARCHAR(10),
    SCHEDULE_DATE DATE,
    SCHEDULE_TYPE VARCHAR(10),
    FOREIGN KEY (C_ID) REFERENCES CUSTOMER(C_ID) ON DELETE CASCADE,
    FOREIGN KEY (SC_ID, MECHANIC_ID) REFERENCES EMPLOYEE(SC_ID, EMP_ID) ON DELETE CASCADE,
    FOREIGN KEY (VIN) REFERENCES VEHICLE(V_IN) ON DELETE CASCADE,
);
CREATE TABLE SERVICEEVENT(
    SC_ID VARCHAR2(20) NOT NULL, 
    C_ID NUMBER(38) NOT NULL, 
    SEVENT_ID VARCHAR2(20) NOT NULL, 
    TOTAL_AMOUNT_PAID NUMBER(38),
    AMOUNT_CHARGED NUMBER(38), 
    S_NO NUMBER(38) NOT NULL, 
    MECHANIC_ID NUMBER(38) NOT NULL, 
    INVOICE_ID NUMBER(38),
    INVOICE_DATE DATE,
    PRIMARY KEY(C_ID, SC_ID, SEVENT_ID, MECHANIC_ID),
    FOREIGN KEY(C_ID, SC_ID) REFERENCES CUSTOMER(C_ID, SC_ID, EMP_ID) ON DELETE CASCADE, 
    FOREIGN KEY(MECHANIC_ID) REFERENCES EMPLOYEE (EMP_ID) ON DELETE CASCADE,
    FOREIGN KEY(S_NO) REFERENCES SERVICES(S_NO) ON DELETE CASCADE
);
CREATE TABLE SERVICES(
  S_NO NUMBER(38) NOT NULL, 
  S_NAME VARCHAR2(20) NOT NULL
  PRIMARY KEY(S_NO)
);
CREATE TABLE SERVICE_CENTER(
    SC_ID VARCHAR2(20) NOT NULL, 
    PHONE_NUMBER NUMBER, 
    ADDRESS VARCHAR2(50), 
    MAX_WAGE NUMBER,
    OPENING_TIME VARCHAR2(20) CONSTRAINT OPENING_TIME CHECK (OPENING_TIME in('8:00 AM', '9:00 AM')),
    CLOSING_TIME VARCHAR(20) CONSTRAINT CLOSING_TIME CHECK (CLOSING_TIME in('8:00 PM', '1:00 PM')),,
    MIN_WAGE NUMBER,
    HOURLY_RATE VARCHAR2(20),
    OPEN_ON_SATURDAY VARCHAR2(10),
    PRIMARY KEY(SC_ID)
);
CREATE TABLE SWAP_REQUEST(
    SC_ID VARCHAR2(20), 
    MECHANIC_ID_1 NUMBER,
    DAY_1 VARCHAR2(10),
    DAY_2 VARCHAR2(10),
    WEEK_1 VARCHAR2(10),
    WEEK_2 VARCHAR2(10),
    START_TIME1 VARCHAR2(10),
    START_TIME2 VARCHAR2(10),
    END_TIME1 VARCHAR2(10),
    END_TIME2 VARCHAR2(10),
    REQUEST_ID VARCHAR2(10) NOT NULL,
    MECHANIC_ID_2 NUMBER,
   PRIMARY KEY(REQUEST_ID),
   FOREIGN KEY(SC_ID, MECHANIC_ID_1) REFERENCES EMPLOYEE (SC_ID, EMP_ID) ON DELETE CASCADE
);
CREATE TABLE TIME_SLOTS(
   START_TIME_SLOT NUMBER,
   END_TIME_SLOT NUMBER,
   START_TIME VARCHAR2(20),
   END_TIME VARCHAR2(20),
);
CREATE TABLE TIRE_SERVICES (
  S_NO NUMBER(38) NOT NULL, 
  FOREIGN KEY (S_NO) REFERENCES SERVICES(S_NO) ON DELETE CASCADE
);
CREATE TABLE TRANSMISSION_SERVICES (
  S_NO NUMBER(38) NOT NULL, 
  FOREIGN KEY (S_NO) REFERENCES SERVICES(S_NO) ON DELETE CASCADE
);
CREATE TABLE VEHICLE (
  VIN VARCHAR2(8) NOT NULL,
  MANUFACTURER VARCHAR2(10) NOT NULL,
  CURRENT_MILEAGE NUMBER(38) NOT NULL,
  YEAR NUMBER,
  PRIMARY KEY(VIN)
);
CREATE TABLE VEHICLE_LAST_SERVICED (
  VIN VARCHAR2(20),
  YEAR NUMBER(10),
  LAST_SCHEDULED_MAINTENANCE_NAME VARCHAR2(10),
  PRIMARY KEY(VIN),
  FOREIGN KEY (VIN) REFERENCES VEHICLE(VIN) ON DELETE CASCADE
);
CREATE TABLE VEHICLE_OWNED(
    SC_ID VARCHAR(20) NOT NULL, 
    C_ID NUMBER(38) NOT NULL, 
    VIN VARCHAR2(8) NOT NULL,
    PRIMARY KEY(SC_ID, C_ID, VIN),
    FOREIGN KEY (VIN) REFERENCES VEHICLE(VIN) ON DELETE CASCADE, 
    FOREIGN KEY(C_ID,SC_ID) REFERENCES CUSTOMER(C_ID,SC_ID) ON DELETE CASCADE
 ); 
CREATE TABLE CART(
  SERVICE_NAME VARCHAR2(20) NOT NULL,
  SERVICE_TYPE VARCHAR(20),
  C_ID NUMBER(38) NOT NULL, 
  VIN VARCHAR2(8) NOT NULL,
  SC_ID VARCHAR(20) NOT NULL,
  PRIMARY KEY (SERVICE_NAME, C_ID, VIN, SC_ID),
  FOREIGN KEY (C_ID,SC_ID) REFERENCES CUSTOMER(C_ID,SC_ID) ON DELETE CASCADE),
  FOREIGN KEY (VIN) REFERENCES VEHICLE(VIN) ON DELETE CASCADE
);
